In [ ]:
import pandas as pd

In [9]:
pd.set_option('display.max_columns', None)

In [ ]:
clean_data_GK_path = '../Data/Clean/GK.csv'
clean_data_Team_path = '../Data/Clean/Team.csv'
clean_data_Player_path = '../Data/Clean/Player.csv'

In [ ]:
player_new = pd.read_csv(clean_data_Player_path)

# player_new['Age'] = player_new['Age'].convert_dtypes()

# print(player_new['Age'].dtypes)

# def convert_age(age_str):
#     years, days = map(int, age_str.split('-'))
#     return years + days / 365  # Assuming 365 days in a year for conversion

# # Apply the conversion to the 'age' column
# player_new['Age'] = player_new['Age'].apply(convert_age)

player_new.drop(['Age'], axis=1)

,Player,#,Nation,Pos,Min,Gls,Ast,PK,PKatt,Sh,...,Stp,Stp%,#OPA,AvgDist,home,game_id,Wk,season,Date,Team Name
0,Ameen Al-Dakhil,28.0,be BEL,CB,90.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
1,Anass Zaroury,19.0,ma MAR,FW,29.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
2,Benson Manuel,10.0,ao ANG,FW,17.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
3,Connor Roberts,14.0,wls WAL,RB,90.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
4,Dara O'Shea,2.0,ie IRL,CB,90.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47391,Jordan Lotomba,23.0,ch SUI,"LB,WB",26.0,1.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47392,Kh√©phren Thuram,19.0,fr FRA,"CM,DM",90.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47393,Mohamed Ali Cho,25.0,fr FRA,"RW,LW",17.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47394,Pablo Rosario,8.0,nl NED,CB,90.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47395,Terem Moffi,9.0,ng NGA,FW,27.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice

In [22]:
player_new_group =  player_new.groupby(['Player', '#', 'Team Name', 'Nation', 'Pos', 'season']).agg({
    'Min': 'mean',
    'Gls': 'mean',
    'Ast': 'mean',
    'PK': 'sum',
    'PKatt': 'sum',
    'Sh': 'mean',
    'SoT': 'mean',
    'CrdY': 'sum',
    'CrdR': 'sum',
    'Touches': 'mean',
    'Tkl': 'mean',
    'Int': 'mean',
    'Blocks': 'mean',
    'xG': 'mean',
    'npxG': 'mean',
    'xAG': 'mean',
    'SCA': 'mean',
    'GCA': 'mean',
    'Cmp_x': 'mean',
    'Att_x': 'mean',
    'Cmp%_x': 'mean',
    'PrgP': 'mean',
    'Carries': 'mean',
    'PrgC': 'mean',
    'Att_x': 'mean',
    'Succ': 'mean',
    'game_id': 'count'       # Total minutes played
}).reset_index()

player_new_group = player_new_group.rename(columns={'game_id': 'total_games'})

In [23]:
player_new_group.head(10)

,Player,#,Team Name,Nation,Pos,season,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Touches,Tkl,Int,Blocks,xG,npxG,xAG,SCA,GCA,Cmp_x,Att_x,Cmp%_x,PrgP,Carries,PrgC,Succ,total_games
0,Aaron Cresswell,3.0,West Ham,eng ENG,CB,2023-2024,30.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.000000,0.500000,0.000000,0.50,0.0,0.0,0.000,0.5,0.000000,25.5,29.50,88.550000,1.500000,14.500000,0.00,0.0,2
1,Aaron Cresswell,3.0,West Ham,eng ENG,"CB,LB",2023-2024,90.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.000000,0.000000,0.000000,1.00,0.0,0.0,0.100,1.0,0.000000,38.0,44.00,86.400000,2.000000,27.000000,1.00,0.0,1
2,Aaron Cresswell,3.0,West Ham,eng ENG,LB,2023-2024,41.333333,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,30.833333,0.166667,0.333333,0.50,0.0,0.0,0.050,1.5,0.166667,23.5,29.00,67.383333,2.666667,15.833333,0.50,0.0,6
3,Aaron Cresswell,3.0,West Ham,eng ENG,LW,2023-2024,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.000,0.0,0.000000,0.0,0.00,NaN,0.000000,0.000000,0.00,0.0,1
4,Aaron Cresswell,3.0,West Ham,eng ENG,RW,2023-2024,37.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.000000,1.000000,1.000000,0.00,0.0,0.0,0.000,1.0,0.000000,24.0,31.00,77.400000,5.000000,18.000000,0.00,0.0,1
5,Aaron Hickey,2.0,Brentford,sct SCO,LB,2023-2024,68.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,33.000000,1.000000,0.000000,1.00,0.0,0.0,0.000,0.0,0.000000,21.0,25.00,84.000000,3.000000,21.000000,1.00,0.0,1
6,Aaron Hickey,2.0,Brentford,sct SCO,"LB,WB",2023-2024,72.000000,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,37.000000,0.000000,0.000000,0.00,0.1,0.1,0.000,0.0,0.000000,29.0,33.00,87.900000,1.000000,22.000000,0.00,0.0,1
7,Aaron Hickey,2.0,Brentford,sct SCO,RB,2023-2024,79.750000,0.0,0.0,0.0,0.0,0.5,0.0,2.0,0.0,48.500000,2.250000,0.500000,0.75,0.0,0.0,0.025,1.5,0.000000,35.0,39.25,89.200000,3.000000,30.250000,0.75,1.0,4
8,Aaron Hickey,2.0,Brentford,sct SCO,"RB,LB",2023-2024,81.000000,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,31.000000,4.000000,0.000000,0.00,0.0,0.0,0.000,1.0,0.000000,16.0,18.00,88.900000,3.000000,19.000000,0.00,1.0,1
9,Aaron Hickey,2.0,Brentford,sct SCO,WB,2023-2024,86.500000,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,30.500000,1.000000,0.500000,1.50,0.0,0.0,0.000,0.0,0.000000,18.5,22.00,84.600000,1.000000,14.500000,2.50,0.0,2

In [24]:
player_new_group.to_csv('../Data/Clean/Player_Gr.csv', index=False)

In [25]:
# print(player_raw_group)
print(player_new_group.loc[player_new_group['Player'] == 'Ameen Al-Dakhil'])

              Player     # Team Name  Nation    Pos     season        Min  \
633  Ameen Al-Dakhil  28.0   Burnley  be BEL     CB  2023-2024  83.571429
634  Ameen Al-Dakhil  28.0   Burnley  be BEL  CB,RB  2023-2024  90.000000
635  Ameen Al-Dakhil  28.0   Burnley  be BEL     LB  2023-2024  55.500000
636  Ameen Al-Dakhil  28.0   Burnley  be BEL  LB,CB  2023-2024  90.000000
637  Ameen Al-Dakhil  28.0   Burnley  be BEL  RB,WB  2023-2024  90.000000

     Gls  Ast   PK  PKatt        Sh       SoT  CrdY  CrdR    Touches  Tkl  \
633  0.0  0.0  0.0    0.0  0.285714  0.142857   1.0   0.0  63.285714  1.0
634  0.0  0.0  0.0    0.0  0.000000  0.000000   0.0   0.0  69.000000  0.0
635  0.0  0.0  0.0    0.0  1.000000  0.500000   0.0   0.0  36.000000  0.5
636  1.0  0.0  0.0    0.0  1.000000  1.000000   0.0   0.0  42.000000  2.0
637  0.0  0.0  0.0    0.0  3.000000  0.000000   0.0   0.0  54.000000  2.0

          Int    Blocks        xG      npxG       xAG       SCA       GCA  \
633  0.571429  0.571429  0.014286  0.014286  0.014286  0.571429  0.142857
634  0.500000  0.500000  0.000000  0.000000  0.000000  0.000000  0.000000
635  1.500000  2.000000  0.050000  0.050000  0.000000  1.000000  0.000000
636  1.000000  3.000000  1.000000  1.000000  0.000000  1.000000  0.000000
637  3.000000  1.000000  0.100000  0.100000  0.000000  1.000000  0.000000

         Cmp_x      Att_x  Cmp%_x      PrgP    Carries      PrgC  Succ  \
633  48.428571  55.428571   86.80  2.571429  45.428571  0.285714   0.0
634  54.500000  64.000000   84.45  4.500000  52.500000  1.500000   1.0
635  20.000000  25.500000   79.40  2.000000  15.500000  0.500000   0.5
636  20.000000  28.000000   71.40  2.000000  11.000000  0.000000   0.0
637  29.000000  42.000000   69.00  2.000000  26.000000  1.000000   0.0

     total_games
633            7
634            2
635            2
636            1
637            1

In [13]:
GK_new = pd.read_csv('../Data/Clean/GK.csv')

# GK_new['Age'] = GK_new['Age'].convert_dtypes()

# print(GK_new['Age'].dtypes)

# def convert_age(age_str):
#     years, days = map(int, age_str.split('-'))
#     return years + days / 365  # Assuming 365 days in a year for conversion

# # Apply the conversion to the 'age' column
# GK_new['Age'] = GK_new['Age'].apply(convert_age)
player_new.drop(['Age'], axis=1)

,Player,#,Nation,Pos,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Touches,Tkl,Int,Blocks,xG,npxG,xAG,SCA,GCA,Cmp_x,Att_x,Cmp%_x,PrgP,Carries,PrgC,Att_x.1,Succ,SoTA,GA,Saves,Save%,PSxG,Cmp_y,Att_y,Cmp%_y,Att (GK),Thr,Launch%,AvgLen,Att_y.1,Launch%.1,AvgLen.1,Opp,Stp,Stp%,#OPA,AvgDist,home,game_id,Wk,season,Date,Team Name
0,Ameen Al-Dakhil,28.0,be BEL,CB,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,32.0,38.0,84.2,3.0,24.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
1,Anass Zaroury,19.0,ma MAR,FW,29.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,10.0,12.0,83.3,0.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
2,Benson Manuel,10.0,ao ANG,FW,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,5.0,80.0,0.0,7.0,1.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
3,Connor Roberts,14.0,wls WAL,RB,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.0,46.0,84.8,4.0,17.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
4,Dara O'Shea,2.0,ie IRL,CB,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,42.0,56.0,75.0,3.0,27.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1.0,2023-2024,2023-08-11,Burnley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47391,Jordan Lotomba,23.0,ch SUI,"LB,WB",26.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,15.0,1.0,2.0,0.0,0.2,0.2,0.0,0.0,0.0,6.0,9.0,66.7,0.0,9.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47392,Kh√©phren Thuram,19.0,fr FRA,"CM,DM",90.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,54.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,40.0,46.0,87.0,2.0,43.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47393,Mohamed Ali Cho,25.0,fr FRA,"RW,LW",17.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.1,1.0,0.0,4.0,4.0,100.0,1.0,5.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47394,Pablo Rosario,8.0,nl NED,CB,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,52.0,56.0,92.9,3.0,52.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice
47395,Terem Moffi,9.0,ng NGA,FW,27.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,5.0,60.0,0.0,2.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,305,34.0,2023-2024,2024-05-19,Nice

In [19]:
GK_new_group =  GK_new.groupby(['Player', '#', 'Team Name', 'Nation', 'Pos', 'season']).agg({
    'Min': 'mean',
    'Gls': 'mean',
    'Ast': 'mean',
    'PK': 'sum',
    'PKatt': 'sum',
    'Sh': 'mean',
    'SoT': 'mean',
    'CrdY': 'sum',
    'CrdR': 'sum',
    'Touches': 'mean',
    'Tkl': 'mean',
    'Int': 'mean',
    'Blocks': 'mean',
    'xG': 'mean',
    'npxG': 'mean',
    'xAG': 'mean',
    'SCA': 'mean',
    'GCA': 'mean',
    'Cmp_x': 'mean',
    'Att_x': 'mean',
    'Cmp%_x': 'mean',
    'PrgP': 'mean',
    'Carries': 'mean',
    'PrgC': 'mean',
    'Att_x': 'mean',
    'Succ': 'mean',
    'SoTA': 'mean',
    'GA': 'mean',
    'Saves': 'mean',
    'Save%': 'mean',
    'PSxG': 'mean',
    'Cmp_y': 'mean',
    'Att_y': 'mean',
    'Cmp%_y': 'mean',
    'Att (GK)': 'mean',
    'Thr': 'mean',
    'Launch%': 'mean',
    'AvgLen': 'mean',
    'Stp': 'sum',
    'Stp%': 'mean',
    '#OPA': 'sum',
    'AvgDist': 'mean',
    'game_id': 'count'       # Total minutes played
}).reset_index()

GK_new_group = GK_new_group.rename(columns={'game_id': 'total_games'})

In [20]:
GK_new_group.head(10)

,Player,#,Team Name,Nation,Pos,season,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Touches,Tkl,Int,Blocks,xG,npxG,xAG,SCA,GCA,Cmp_x,Att_x,Cmp%_x,PrgP,Carries,PrgC,Succ,SoTA,GA,Saves,Save%,PSxG,Cmp_y,Att_y,Cmp%_y,Att (GK),Thr,Launch%,AvgLen,Stp,Stp%,#OPA,AvgDist,total_games
0,Aaron Ramsdale,1.0,Arsenal,eng ENG,GK,2023-2024,90.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.833333,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,21.833333,31.333333,70.650000,0.333333,22.833333,0.0,0.000000,2.333333,0.833333,1.500000,68.050000,0.600000,3.166667,11.500000,33.566667,28.166667,5.000000,33.350000,32.600000,8.0,16.633333,9.0,14.840000,6
1,Aar√≥n Escandell,1.0,Las Palmas,es ESP,GK,2023-2024,76.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,32.000000,43.000000,70.700000,0.000000,21.000000,0.0,0.000000,2.000000,1.500000,0.500000,16.650000,1.200000,4.500000,13.000000,34.150000,36.500000,5.000000,33.300000,32.500000,1.0,5.550000,4.0,18.800000,2
2,Aitor Fern√°ndez,13.0,Osasuna,es ESP,GK,2023-2024,78.714286,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,30.857143,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.142857,0.0,18.142857,28.285714,64.585714,0.142857,16.000000,0.0,0.000000,2.857143,1.285714,1.571429,54.166667,0.885714,6.714286,16.142857,43.528571,24.857143,2.714286,57.342857,42.842857,1.0,1.428571,15.0,23.871429,7
3,Alaa Bellaarouch,36.0,Strasbourg,ma MAR,GK,2023-2024,90.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,36.133333,0.000000,0.066667,0.0,0.0,0.0,0.000000,0.066667,0.0,23.466667,33.600000,70.640000,0.000000,27.666667,0.0,0.000000,4.200000,1.733333,2.466667,62.021429,1.320000,3.733333,12.200000,32.053333,29.333333,3.800000,36.740000,34.706667,19.0,9.993333,21.0,12.733333,15
4,Alban Lafont,1.0,Nantes,fr FRA,GK,2023-2024,89.142857,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,38.607143,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.214286,0.0,25.714286,35.928571,71.789286,0.107143,27.428571,0.0,0.000000,4.214286,1.535714,2.678571,70.566667,1.507143,4.392857,13.857143,33.635714,29.964286,5.178571,34.164286,33.967857,33.0,8.878571,33.0,12.353846,28
5,Alessandro Sorrentino,23.0,Monza,it ITA,GK,2023-2024,78.285714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.285714,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.142857,0.0,21.142857,27.571429,75.285714,0.000000,14.142857,0.0,0.142857,4.571429,2.285714,2.285714,64.585714,2.042857,2.571429,8.000000,35.928571,21.571429,4.142857,27.642857,31.057143,3.0,5.014286,3.0,15.375000,7
6,Alessio Cragno,28.0,Sassuolo,it ITA,GK,2023-2024,90.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.666667,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,23.000000,33.333333,68.866667,0.000000,18.000000,0.0,0.000000,4.666667,2.333333,2.666667,44.433333,1.733333,5.666667,15.000000,38.833333,26.000000,3.666667,51.300000,38.466667,3.0,9.100000,8.0,18.650000,3
7,Alex Meret,1.0,Napoli,it ITA,GK,2023-2024,89.451613,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.935484,0.032258,0.000000,0.0,0.0,0.0,0.003226,0.161290,0.0,24.806452,29.483871,84.529032,0.000000,18.193548,0.0,0.032258,3.354839,1.333333,2.000000,58.586207,1.219355,1.806452,5.612903,30.851613,24.967742,3.870968,18.683333,27.796774,9.0,3.570000,29.0,15.500000,31
8,Alexander Brunst,30.0,Darmstadt 98,de GER,GK,2023-2024,90.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.666667,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.666667,0.0,34.333333,50.000000,67.966667,0.000000,29.666667,0.0,0.000000,5.666667,3.333333,2.333333,46.033333,2.066667,11.000000,24.000000,48.966667,43.000000,4.333333,42.466667,36.633333,3.0,5.333333,9.0,17.733333,3
9,Alexander Meyer,33.0,Dortmund,de GER,GK,2023-2024,86.875000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.750000,0.125000,0.000000,0.0,0.0,0.0,0.000000,0.125000,0.0,37.750000,45.750000,83.450000,0.125000,33.750000,0.0,0.125000,3.375000,1.125000,2.375000,71.185714,0.962500,3.375000,10.125000,31.225000,41.750000,3.625000,20.225000,28.037500,8.0,9.337500,7.0,13.075000,8

In [21]:
player_new_group.to_csv('../Data/Clean/GK_Gr.csv', index=False)