In [404]:
import pandas as pd
import os
from datetime import datetime 
import seaborn as sns
import matplotlib.pyplot as plt

In [405]:
pd.set_option('display.max_columns', None)

In [406]:
players = pd.read_csv('../Data/RAW/Transfermarkt_Dataset/shortenplayers.csv')
players.head(10)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,1978-05-08 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
3,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000.0,3000000.0
4,123,Christoph,Metzelder,Christoph Metzelder,2012,33,christoph-metzelder,Germany,Haltern,Germany,1980-11-05 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/christoph-metz...,L1,FC Schalke 04,1500000.0,9500000.0
5,132,Tomas,Rosicky,Tomas Rosicky,2015,11,tomas-rosicky,CSSR,Praha,Czech Republic,1980-10-04 00:00:00,Attacking Midfield,Midfield,both,179.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tomas-rosicky/...,GB1,Arsenal Football Club,350000.0,17500000.0
6,162,Marc,Ziegler,Marc Ziegler,2012,79,marc-ziegler,Germany,Blieskastel,Germany,1976-06-13 00:00:00,Goalkeeper,Goalkeeper,right,193.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/marc-ziegler/p...,L1,Verein für Bewegungsspiele Stuttgart 1893,200000.0,1250000.0
7,215,Roque,Santa Cruz,Roque Santa Cruz,2015,1084,roque-santa-cruz,Paraguay,Asunción,Paraguay,1981-08-16 00:00:00,Centre-Forward,Attack,right,193.0,2023-12-31 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roque-santa-cr...,ES1,Málaga CF,250000.0,12000000.0
8,258,Gerald,Asamoah,Gerald Asamoah,2013,33,gerald-asamoah,Ghana,Mampong,Germany,1978-10-03 00:00:00,Centre-Forward,Attack,right,180.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/gerald-asamoah...,L1,FC Schalke 04,100000.0,7000000.0
9,264,Tamás,Hajnal,Tamás Hajnal,2012,79,tamas-hajnal,Hungary,Esztergom,Hungary,1981-03-15 00:00:00,Attacking Midfield,Midfield,both,167.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tamas-hajnal/p...,L1,Verein für Bewegungsspiele Stuttgart 1893,100000.0,6500000.0

In [407]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11661 entries, 0 to 11660
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             11661 non-null  int64
 1   first_name                            11215 non-null  object
 2   last_name                             11661 non-null  object
 3   name                                  11661 non-null  object
 4   last_season                           11661 non-null  int64
 5   current_club_id                       11661 non-null  int64
 6   player_code                           11661 non-null  object
 7   country_of_birth                      11163 non-null  object
 8   city_of_birth                         11276 non-null  object
 9   country_of_citizenship                11536 non-null  object
 10  date_of_birth                         11638 non-null  object
 11  sub_position                          11629 non-null  object
 12  position                              11661 non-null  object
 13  foot                                  10881 non-null  object
 14  height_in_cm                          10916 non-null  float64
 15  contract_expiration_date              7695 non-null   object
 16  agent_name                            6773 non-null   object
 17  image_url                             11661 non-null  object
 18  url                                   11661 non-null  object
 19  current_club_domestic_competition_id  11661 non-null  object
 20  current_club_name                     11661 non-null  object
 21  market_value_in_eur                   11261 non-null  float64
 22  highest_market_value_in_eur           11261 non-null  float64
dtypes: float64(3), int64(3), object(17)
memory usage: 2.0+ MB

In [408]:
# Replace 'col1' and 'col2' with your chosen columns
key_columns = ['name', 'current_club_name']

# Check uniqueness in df1
is_unique_df1 = not players.duplicated(subset=key_columns).any()


print(f"Unique in df1: {is_unique_df1}")

Unique in df1: False

In [409]:
duplicates_df1 = players[players.duplicated(subset=key_columns, keep=False)]
 
print("Duplicates in df1:")
print(duplicates_df1.count())

Duplicates in df1:
player_id                               4
first_name                              4
last_name                               4
name                                    4
last_season                             4
current_club_id                         4
player_code                             4
country_of_birth                        3
city_of_birth                           3
country_of_citizenship                  4
date_of_birth                           3
sub_position                            4
position                                4
foot                                    3
height_in_cm                            3
contract_expiration_date                1
agent_name                              1
image_url                               4
url                                     4
current_club_domestic_competition_id    4
current_club_name                       4
market_value_in_eur                     3
highest_market_value_in_eur             3
dtype: int64

In [410]:
transfer = pd.read_csv('../Data/RAW/Transfermarkt_Dataset/transfers.csv')
transfer.head(10)

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,195778,2026-06-30,25/26,79,27,VfB Stuttgart,Bayern Munich,0.0,12000000.0,Alexander Nübel
1,569033,2026-06-30,25/26,39,27,1.FSV Mainz 05,Bayern Munich,0.0,4000000.0,Armindo Sieb
2,626913,2026-06-30,25/26,398,380,Lazio,Salernitana,0.0,15000000.0,Boulaye Dia
3,1047109,2026-06-30,25/26,2672,265,APO Levadiakos,Panathinaikos,0.0,100000.0,Georgios Katris
4,360791,2025-12-31,25/26,6418,1030,Panetolikos,Argentinos Jrs.,0.0,1200000.0,Lucas Chaves
5,532536,2025-10-24,24/25,2451,1519,Inverness CT,Dundee United,0.0,150000.0,Jack Newman
6,1038821,2025-07-31,25/26,3837,11204,Fredrikstad,Stade Reims B,0.0,100000.0,Fallou Fall
7,55336,2025-07-01,25/26,3719,123,Khimki,Retired,NaN,150000.0,Denis Glushakov
8,149729,2025-07-01,25/26,294,114,Benfica,Besiktas,2000000.0,3800000.0,João Mário
9,160506,2025-07-01,25/26,206,515,Bröndby IF,Without Club,0.0,1500000.0,Josip Radosevic

In [411]:
transfer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77936 entries, 0 to 77935
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            77936 non-null  int64
 1   transfer_date        77936 non-null  object
 2   transfer_season      77936 non-null  object
 3   from_club_id         77936 non-null  int64
 4   to_club_id           77936 non-null  int64
 5   from_club_name       77936 non-null  object
 6   to_club_name         77936 non-null  object
 7   transfer_fee         50774 non-null  float64
 8   market_value_in_eur  48243 non-null  float64
 9   player_name          77936 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 5.9+ MB

In [412]:
# Filter the dataset for transfer after 2020
#transfer = transfer[(transfer['transfer_season'] >= 20/21)]
transfer['transfer_date'] = pd.to_datetime(transfer['transfer_date'])

# Filter the data within the date range
transfer = transfer[
    #(transfer['transfer_date'] >= '2017-01-01') & 
    (transfer['transfer_date'] <= '2025-12-31')
]

In [413]:
transfer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77932 entries, 4 to 77935
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            77932 non-null  int64
 1   transfer_date        77932 non-null  datetime64[ns]
 2   transfer_season      77932 non-null  object
 3   from_club_id         77932 non-null  int64
 4   to_club_id           77932 non-null  int64
 5   from_club_name       77932 non-null  object
 6   to_club_name         77932 non-null  object
 7   transfer_fee         50770 non-null  float64
 8   market_value_in_eur  48239 non-null  float64
 9   player_name          77932 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(4)
memory usage: 6.5+ MB

In [414]:
transfer.isnull().sum()

player_id                  0
transfer_date              0
transfer_season            0
from_club_id               0
to_club_id                 0
from_club_name             0
to_club_name               0
transfer_fee           27162
market_value_in_eur    29693
player_name                0
dtype: int64

In [415]:
transfer.head()

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
4,360791,2025-12-31,25/26,6418,1030,Panetolikos,Argentinos Jrs.,0.0,1200000.0,Lucas Chaves
5,532536,2025-10-24,24/25,2451,1519,Inverness CT,Dundee United,0.0,150000.0,Jack Newman
6,1038821,2025-07-31,25/26,3837,11204,Fredrikstad,Stade Reims B,0.0,100000.0,Fallou Fall
7,55336,2025-07-01,25/26,3719,123,Khimki,Retired,NaN,150000.0,Denis Glushakov
8,149729,2025-07-01,25/26,294,114,Benfica,Besiktas,2000000.0,3800000.0,João Mário

In [416]:
merged_df = pd.merge(players, transfer, 
                     left_on=['player_id'], 
                     right_on=['player_id'], 
                     how='left')

In [417]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37153 entries, 0 to 37152
Data columns (total 32 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             37153 non-null  int64
 1   first_name                            35746 non-null  object
 2   last_name                             37153 non-null  object
 3   name                                  37153 non-null  object
 4   last_season                           37153 non-null  int64
 5   current_club_id                       37153 non-null  int64
 6   player_code                           37153 non-null  object
 7   country_of_birth                      36255 non-null  object
 8   city_of_birth                         36368 non-null  object
 9   country_of_citizenship                37028 non-null  object
 10  date_of_birth                         37126 non-null  object
 11  sub_position                          37119 non-null  object
 12  position                              37153 non-null  object
 13  foot                                  35879 non-null  object
 14  height_in_cm                          35962 non-null  float64
 15  contract_expiration_date              30341 non-null  object
 16  agent_name                            25512 non-null  object
 17  image_url                             37153 non-null  object
 18  url                                   37153 non-null  object
 19  current_club_domestic_competition_id  37153 non-null  object
 20  current_club_name                     37153 non-null  object
 21  market_value_in_eur_x                 36482 non-null  float64
 22  highest_market_value_in_eur           36482 non-null  float64
 23  transfer_date                         29509 non-null  datetime64[ns]
 24  transfer_season                       29509 non-null  object
 25  from_club_id                          29509 non-null  float64
 26  to_club_id                            29509 non-null  float64
 27  from_club_name                        29509 non-null  object
 28  to_club_name                          29509 non-null  object
 29  transfer_fee                          19288 non-null  float64
 30  market_value_in_eur_y                 18135 non-null  float64
 31  player_name                           29509 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(3), object(21)
memory usage: 9.1+ MB

In [418]:
merged_df.isnull().sum()

player_id                                   0
first_name                               1407
last_name                                   0
name                                        0
last_season                                 0
current_club_id                             0
player_code                                 0
country_of_birth                          898
city_of_birth                             785
country_of_citizenship                    125
date_of_birth                              27
sub_position                               34
position                                    0
foot                                     1274
height_in_cm                             1191
contract_expiration_date                 6812
agent_name                              11641
image_url                                   0
url                                         0
current_club_domestic_competition_id        0
current_club_name                           0
market_value_in_eur_x                     671
highest_market_value_in_eur               671
transfer_date                            7644
transfer_season                          7644
from_club_id                             7644
to_club_id                               7644
from_club_name                           7644
to_club_name                             7644
transfer_fee                            17865
market_value_in_eur_y                   19018
player_name                              7644
dtype: int64

In [419]:
merged_df.head(10)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur_x,highest_market_value_in_eur,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur_y,player_name
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,1978-05-08 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000.0,3000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,123,Christoph,Metzelder,Christoph Metzelder,2012,33,christoph-metzelder,Germany,Haltern,Germany,1980-11-05 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/christoph-metz...,L1,FC Schalke 04,1500000.0,9500000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,132,Tomas,Rosicky,Tomas Rosicky,2015,11,tomas-rosicky,CSSR,Praha,Czech Republic,1980-10-04 00:00:00,Attacking Midfield,Midfield,both,179.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tomas-rosicky/...,GB1,Arsenal Football Club,350000.0,17500000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,162,Marc,Ziegler,Marc Ziegler,2012,79,marc-ziegler,Germany,Blieskastel,Germany,1976-06-13 00:00:00,Goalkeeper,Goalkeeper,right,193.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/marc-ziegler/p...,L1,Verein für Bewegungsspiele Stuttgart 1893,200000.0,1250000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,215,Roque,Santa Cruz,Roque Santa Cruz,2015,1084,roque-santa-cruz,Paraguay,Asunción,Paraguay,1981-08-16 00:00:00,Centre-Forward,Attack,right,193.0,2023-12-31 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roque-santa-cr...,ES1,Málaga CF,250000.0,12000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,258,Gerald,Asamoah,Gerald Asamoah,2013,33,gerald-asamoah,Ghana,Mampong,Germany,1978-10-03 00:00:00,Centre-Forward,Attack,right,180.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/gerald-asamoah...,L1,FC Schalke 04,100000.0,7000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,264,Tamás,Hajnal,Tamás Hajnal,2012,79,tamas-hajnal,Hungary,Esztergom,Hungary,1981-03-15 00:00:00,Attacking Midfield,Midfield,both,167.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tamas-hajnal/p...,L1,Verein für Bewegungsspiele Stuttgart 1893,100000.0,6500000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [420]:
dup_rows = merged_df[merged_df['player_id'].duplicated()]
dup_rows.head(10)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur_x,highest_market_value_in_eur,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur_y,player_name
137,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2015-07-01,15/16,281.0,31.0,Man City,Liverpool,0.0,14000000.0,James Milner
138,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2010-08-17,10/11,405.0,281.0,Aston Villa,Man City,22000000.0,20000000.0,James Milner
139,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2008-08-29,08/09,762.0,405.0,Newcastle,Aston Villa,15000000.0,8750000.0,James Milner
140,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2006-05-08,05/06,405.0,762.0,Aston Villa,Newcastle,0.0,4700000.0,James Milner
141,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2005-08-31,05/06,762.0,405.0,Newcastle,Aston Villa,0.0,5500000.0,James Milner
142,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2004-07-02,04/05,399.0,762.0,Leeds,Newcastle,7400000.0,NaN,James Milner
143,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2003-10-02,03/04,352.0,399.0,Swindon Town,Leeds,0.0,NaN,James Milner
144,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2003-09-04,03/04,399.0,352.0,Leeds,Swindon Town,0.0,NaN,James Milner
145,3333,James,Milner,James Milner,2024,1237,james-milner,England,Leeds,England,1986-01-04 00:00:00,Central Midfield,Midfield,right,175.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0,2002-07-01,02/03,10161.0,399.0,Leeds U18,Leeds,NaN,NaN,James Milner
404,7161,Jonas,Hofmann,Jonas Hofmann,2024,15,jonas-hofmann,Germany,Heidelberg,Germany,1992-07-14 00:00:00,Attacking Midfield,Midfield,right,176.0,2027-06-30 00:00:00,Dr. Marco Gutfleisch,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/jonas-hofmann/...,L1,Bayer 04 Leverkusen Fußball,7000000.0,16000000.0,2016-01-01,15/16,16.0,18.0,Bor. Dortmund,Bor. M'gladbach,8000000.0,4000000.0,Jonas Hofmann

In [421]:
nan_rows = merged_df[merged_df['player_name'].isna()]

In [422]:
nan_rows.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur_x,highest_market_value_in_eur,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur_y,player_name
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,1978-05-08 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000.0,3000000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,123,Christoph,Metzelder,Christoph Metzelder,2012,33,christoph-metzelder,Germany,Haltern,Germany,1980-11-05 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/christoph-metz...,L1,FC Schalke 04,1500000.0,9500000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [423]:
# Reformat the season
merged_df['transfer_season'] = merged_df['transfer_season'].astype(str).apply(lambda x: f"20{x[:2]}-20{x[3:]}")

In [424]:
merged_df = merged_df.rename(columns={'to_club_name': 'club'})

In [425]:
merged_df.drop(columns=['first_name', 'last_name', 'player_code', 'sub_position', 'position', 'url', 'agent_name', 'current_club_domestic_competition_id', 'from_club_id', 'from_club_name'], inplace=True)

In [426]:
print(merged_df.loc[(merged_df['name'] == 'Aaron Wan-Bissaka')])

       player_id               name  last_season  current_club_id  \
25574     477758  Aaron Wan-Bissaka         2024              379
25575     477758  Aaron Wan-Bissaka         2024              379
25576     477758  Aaron Wan-Bissaka         2024              379
25577     477758  Aaron Wan-Bissaka         2024              379

      country_of_birth city_of_birth country_of_citizenship  \
25574          England        London                England
25575          England        London                England
25576          England        London                England
25577          England        London                England

             date_of_birth   foot  height_in_cm contract_expiration_date  \
25574  1997-11-26 00:00:00  right         183.0      2031-06-30 00:00:00
25575  1997-11-26 00:00:00  right         183.0      2031-06-30 00:00:00
25576  1997-11-26 00:00:00  right         183.0      2031-06-30 00:00:00
25577  1997-11-26 00:00:00  right         183.0      2031-06-30 00:00:00

                                               image_url  \
25574  https://img.a.transfermarkt.technology/portrai...
25575  https://img.a.transfermarkt.technology/portrai...
25576  https://img.a.transfermarkt.technology/portrai...
25577  https://img.a.transfermarkt.technology/portrai...

                current_club_name  market_value_in_eur_x  \
25574  West Ham Utd Football Club             20000000.0
25575  West Ham Utd Football Club             20000000.0
25576  West Ham Utd Football Club             20000000.0
25577  West Ham Utd Football Club             20000000.0

       highest_market_value_in_eur transfer_date transfer_season  to_club_id  \
25574                   40000000.0    2024-08-13       2024-2025       379.0
25575                   40000000.0    2019-07-01       2019-2020       985.0
25576                   40000000.0    2018-01-01       2017-2018       873.0
25577                   40000000.0    2016-07-01       2016-2017      6945.0

                 club  transfer_fee  market_value_in_eur_y        player_name
25574        West Ham    17600000.0             20000000.0  Aaron Wan-Bissaka
25575         Man Utd    55000000.0             35000000.0  Aaron Wan-Bissaka
25576  Crystal Palace           NaN                    NaN  Aaron Wan-Bissaka
25577      Palace U21           NaN                    NaN  Aaron Wan-Bissaka

In [427]:
# Create a mapping from club_id to current_club_name
club_id_to_name = merged_df.set_index('current_club_id')['current_club_name'].to_dict()

# Apply the mapping to rename the 'club' column
merged_df['club'] = merged_df['to_club_id'].map(club_id_to_name).fillna(merged_df['club'])

merged_df['club'].fillna(merged_df['current_club_name'], inplace=True)
# Filter rows where club is not NaN
non_nan_club = merged_df[merged_df['club'].notna()]

# Duplicate and modify the 'club' value
duplicated_rows = non_nan_club.copy()
duplicated_rows['club'] = duplicated_rows['current_club_name']

# Concatenate back to original DataFrame
merged_df = pd.concat([merged_df, duplicated_rows], ignore_index=True)

C:\Users\MY LAPTOP\AppData\Local\Temp\ipykernel_25780\3160350087.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['club'].fillna(merged_df['current_club_name'], inplace=True)

In [428]:
merged_df.head()

,player_id,name,last_season,current_club_id,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,foot,height_in_cm,contract_expiration_date,image_url,current_club_name,market_value_in_eur_x,highest_market_value_in_eur,transfer_date,transfer_season,to_club_id,club,transfer_fee,market_value_in_eur_y,player_name
0,10,Miroslav Klose,2015,398,Poland,Opole,Germany,1978-06-09 00:00:00,right,184.0,NaN,https://img.a.transfermarkt.technology/portrai...,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,NaT,20na-20,NaN,Società Sportiva Lazio S.p.A.,NaN,NaN,NaN
1,26,Roman Weidenfeller,2017,16,Germany,Diez,Germany,1980-08-06 00:00:00,left,190.0,NaN,https://img.a.transfermarkt.technology/portrai...,Borussia Dortmund,750000.0,8000000.0,NaT,20na-20,NaN,Borussia Dortmund,NaN,NaN,NaN
2,77,Lúcio,2012,506,Brazil,Brasília,Brazil,1978-05-08 00:00:00,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,Juventus Football Club,200000.0,24500000.0,NaT,20na-20,NaN,Juventus Football Club,NaN,NaN,NaN
3,80,Tom Starke,2017,27,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,right,194.0,NaN,https://img.a.transfermarkt.technology/portrai...,Bayern Munich,100000.0,3000000.0,NaT,20na-20,NaN,Bayern Munich,NaN,NaN,NaN
4,123,Christoph Metzelder,2012,33,Germany,Haltern,Germany,1980-11-05 00:00:00,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,FC Schalke 04,1500000.0,9500000.0,NaT,20na-20,NaN,FC Schalke 04,NaN,NaN,NaN

In [429]:
# Replace 'col1' and 'col2' with your chosen columns
key_columns = ['name', 'club']

# Check uniqueness in df1
is_unique_df1 = not merged_df.duplicated(subset=key_columns).any()


print(f"Unique in df1: {is_unique_df1}")

Unique in df1: False

In [430]:
duplicates_df2 = merged_df[merged_df.duplicated(subset=key_columns, keep=False)]
 
print("Duplicates in df1:")
print(duplicates_df2.count())

Duplicates in df1:
player_id                      58155
name                           58155
last_season                    58155
current_club_id                58155
country_of_birth               56769
city_of_birth                  56995
country_of_citizenship         57905
date_of_birth                  58106
foot                           56118
height_in_cm                   56317
contract_expiration_date       46484
image_url                      58155
current_club_name              58155
market_value_in_eur_x          57185
highest_market_value_in_eur    57185
transfer_date                  42867
transfer_season                58155
to_club_id                     42867
club                           58155
transfer_fee                   30282
market_value_in_eur_y          29638
player_name                    42867
dtype: int64

In [431]:
duplicates_df2.head(10)

,player_id,name,last_season,current_club_id,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,foot,height_in_cm,contract_expiration_date,image_url,current_club_name,market_value_in_eur_x,highest_market_value_in_eur,transfer_date,transfer_season,to_club_id,club,transfer_fee,market_value_in_eur_y,player_name
0,10,Miroslav Klose,2015,398,Poland,Opole,Germany,1978-06-09 00:00:00,right,184.0,NaN,https://img.a.transfermarkt.technology/portrai...,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,NaT,20na-20,NaN,Società Sportiva Lazio S.p.A.,NaN,NaN,NaN
1,26,Roman Weidenfeller,2017,16,Germany,Diez,Germany,1980-08-06 00:00:00,left,190.0,NaN,https://img.a.transfermarkt.technology/portrai...,Borussia Dortmund,750000.0,8000000.0,NaT,20na-20,NaN,Borussia Dortmund,NaN,NaN,NaN
2,77,Lúcio,2012,506,Brazil,Brasília,Brazil,1978-05-08 00:00:00,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,Juventus Football Club,200000.0,24500000.0,NaT,20na-20,NaN,Juventus Football Club,NaN,NaN,NaN
3,80,Tom Starke,2017,27,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,right,194.0,NaN,https://img.a.transfermarkt.technology/portrai...,Bayern Munich,100000.0,3000000.0,NaT,20na-20,NaN,Bayern Munich,NaN,NaN,NaN
4,123,Christoph Metzelder,2012,33,Germany,Haltern,Germany,1980-11-05 00:00:00,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,FC Schalke 04,1500000.0,9500000.0,NaT,20na-20,NaN,FC Schalke 04,NaN,NaN,NaN
5,132,Tomas Rosicky,2015,11,CSSR,Praha,Czech Republic,1980-10-04 00:00:00,both,179.0,NaN,https://img.a.transfermarkt.technology/portrai...,Arsenal Football Club,350000.0,17500000.0,NaT,20na-20,NaN,Arsenal Football Club,NaN,NaN,NaN
6,162,Marc Ziegler,2012,79,Germany,Blieskastel,Germany,1976-06-13 00:00:00,right,193.0,NaN,https://img.a.transfermarkt.technology/portrai...,Verein für Bewegungsspiele Stuttgart 1893,200000.0,1250000.0,NaT,20na-20,NaN,Verein für Bewegungsspiele Stuttgart 1893,NaN,NaN,NaN
7,215,Roque Santa Cruz,2015,1084,Paraguay,Asunción,Paraguay,1981-08-16 00:00:00,right,193.0,2023-12-31 00:00:00,https://img.a.transfermarkt.technology/portrai...,Málaga CF,250000.0,12000000.0,NaT,20na-20,NaN,Málaga CF,NaN,NaN,NaN
8,258,Gerald Asamoah,2013,33,Ghana,Mampong,Germany,1978-10-03 00:00:00,right,180.0,NaN,https://img.a.transfermarkt.technology/portrai...,FC Schalke 04,100000.0,7000000.0,NaT,20na-20,NaN,FC Schalke 04,NaN,NaN,NaN
9,264,Tamás Hajnal,2012,79,Hungary,Esztergom,Hungary,1981-03-15 00:00:00,both,167.0,NaN,https://img.a.transfermarkt.technology/portrai...,Verein für Bewegungsspiele Stuttgart 1893,100000.0,6500000.0,NaT,20na-20,NaN,Verein für Bewegungsspiele Stuttgart 1893,NaN,NaN,NaN

In [432]:
identify = merged_df[['player_id', 'name', 'club']]

In [433]:
identify.head(10)

   player_id                 name                                       club
0         10       Miroslav Klose              Società Sportiva Lazio S.p.A.
1         26   Roman Weidenfeller                          Borussia Dortmund
2         77                Lúcio                     Juventus Football Club
3         80           Tom Starke                              Bayern Munich
4        123  Christoph Metzelder                              FC Schalke 04
5        132        Tomas Rosicky                      Arsenal Football Club
6        162         Marc Ziegler  Verein für Bewegungsspiele Stuttgart 1893
7        215     Roque Santa Cruz                                  Málaga CF
8        258       Gerald Asamoah                              FC Schalke 04
9        264         Tamás Hajnal  Verein für Bewegungsspiele Stuttgart 1893

In [434]:
duplicate = identify[identify.duplicated()]
 
print("Duplicate Rows :")
 
# Print the resultant Dataframe
duplicate

Duplicate Rows :

       player_id           name                                   club
141         3333   James Milner              Aston Villa Football Club
142         3333   James Milner            Newcastle Utd Football Club
145         3333   James Milner                           Leeds United
407         7161  Jonas Hofmann                      Borussia Dortmund
461         7825     Pepe Reina              Associazione Calcio Milan
...          ...            ...                                    ...
74300    1247360   Ivan M'Bahia                       Clermont Foot 63
74301    1247360   Ivan M'Bahia                       Clermont Foot 63
74303    1255616  Alberto Risco  Getafe Club  Fútbol S.A.D. Team Dubai
74304    1255616  Alberto Risco  Getafe Club  Fútbol S.A.D. Team Dubai
74305    1296876  Marc Domènech    Real Club Deportivo Mallorca S.A.D.

[43202 rows x 3 columns]

In [435]:
identify = identify.drop_duplicates()

In [436]:
identify.to_csv('../Data/identify.csv', index=False)