In [23]:
import pandas as pd

In [24]:
fixture_raw = pd.read_csv('../Data/Raw/la-liga_2021-2022_fixture_data.csv')
# player_raw = pd.read_csv('../la-liga_2021-2022_player_data.csv')

In [25]:
pd.set_option('display.max_columns', None)

In [26]:
fixture_raw.head(10)

,Wk,Day,Date,Time,Home,Away,xG,xG.1,Score,season,game_id
0,1.0,Fri,2021-08-13,21:00,Valencia,Getafe,1.5,1.4,1–0,2021-2022,0
1,1.0,Sat,2021-08-14,19:30,Mallorca,Betis,0.5,0.6,1–1,2021-2022,1
2,1.0,Sat,2021-08-14,19:30,Cádiz,Levante,0.6,0.9,1–1,2021-2022,2
3,1.0,Sat,2021-08-14,22:00,Alavés,Real Madrid,1.7,1.7,1–4,2021-2022,3
4,1.0,Sat,2021-08-14,22:00,Osasuna,Espanyol,0.9,0.5,0–0,2021-2022,4
5,1.0,Sun,2021-08-15,17:30,Celta Vigo,Atlético Madrid,2.3,1.5,1–2,2021-2022,5
6,1.0,Sun,2021-08-15,20:00,Barcelona,Real Sociedad,2.8,0.8,4–2,2021-2022,6
7,1.0,Sun,2021-08-15,22:15,Sevilla,Rayo Vallecano,3.7,0.4,3–0,2021-2022,7
8,1.0,Mon,2021-08-16,20:00,Villarreal,Granada,1.1,0.3,0–0,2021-2022,8
9,1.0,Mon,2021-08-16,22:00,Elche,Athletic Club,1.1,0.6,0–0,2021-2022,9

In [27]:
fixture_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Wk       380 non-null    float64
 1   Day      380 non-null    object
 2   Date     380 non-null    object
 3   Time     380 non-null    object
 4   Home     380 non-null    object
 5   Away     380 non-null    object
 6   xG       380 non-null    float64
 7   xG.1     380 non-null    float64
 8   Score    380 non-null    object
 9   season   380 non-null    object
 10  game_id  380 non-null    int64
dtypes: float64(3), int64(1), object(7)
memory usage: 32.8+ KB

In [28]:
fixture_raw.describe()

               Wk          xG        xG.1     game_id
count  380.000000  380.000000  380.000000  380.000000
mean    19.500000    1.372105    1.054737  211.194737
std     10.980313    0.796901    0.736141  123.458619
min      1.000000    0.100000    0.100000    0.000000
25%     10.000000    0.800000    0.500000  103.750000
50%     19.500000    1.200000    0.900000  211.500000
75%     29.000000    1.800000    1.400000  318.250000
max     38.000000    4.400000    4.900000  423.000000

In [29]:
fixture_raw.isnull().sum()

Wk         0
Day        0
Date       0
Time       0
Home       0
Away       0
xG         0
xG.1       0
Score      0
season     0
game_id    0
dtype: int64